export default {
  el: {
    colorpicker: {
      confirm: '确定',
      clear: '清空'
    },
    datepicker: {
      now: '此刻',
      today: '今天',
      cancel: '取消',
      clear: '清空',
      confirm: '确定',
      selectDate: '选择日期',
      selectTime: '选择时间',
      startDate: '开始日期',
      startTime: '开始时间',
      endDate: '结束日期',
      endTime: '结束时间',
      prevYear: '前一年',
      nextYear: '后一年',
      prevMonth: '上个月',
      nextMonth: '下个月',
      year: '年',
      month1: '1 月',
      month2: '2 月',
      month3: '3 月',
      month4: '4 月',
      month5: '5 月',
      month6: '6 月',
      month7: '7 月',
      month8: '8 月',
      month9: '9 月',
      month10: '10 月',
      month11: '11 月',
      month12: '12 月',
      // week: '周次',
      weeks: {
        sun: '日',
        mon: '一',
        tue: '二',
        wed: '三',
        thu: '四',
        fri: '五',
        sat: '六'
      },
      months: {
        jan: '一月',
        feb: '二月',
        mar: '三月',
        apr: '四月',
        may: '五月',
        jun: '六月',
        jul: '七月',
        aug: '八月',
        sep: '九月',
        oct: '十月',
        nov: '十一月',
        dec: '十二月'
      }
    },
    select: {
      loading: '加载中',
      noMatch: '无匹配数据',
      noData: '无数据',
      placeholder: '请选择'
    },
    cascader: {
      noMatch: '无匹配数据',
      loading: '加载中',
      placeholder: '请选择',
      noData: '暂无数据'
    },
    pagination: {
      goto: '前往',
      pagesize: '条/页',
      total: '共 {total} 条',
      pageClassifier: '页'
    },
    messagebox: {
      title: '提示',
      confirm: '确定',
      cancel: '取消',
      error: '输入的数据不合法!'
    },
    upload: {
      deleteTip: '按 delete 键可删除',
      delete: '删除',
      preview: '查看图片',
      continue: '继续上传'
    },
    table: {
      emptyText: '暂无数据',
      confirmFilter: '筛选',
      resetFilter: '重置',
      clearFilter: '全部',
      sumText: '合计'
    },
    tree: {
      emptyText: '暂无数据'
    },
    transfer: {
      noMatch: '无匹配数据',
      noData: '无数据',
      titles: ['列表 1', '列表 2'],
      filterPlaceholder: '请输入搜索内容',
      noCheckedFormat: '共 {total} 项',
      hasCheckedFormat: '已选 {checked}/{total} 项'
    },
    image: {
      error: '加载失败'
    },
    pageHeader: {
      title: '返回'
    },
    popconfirm: {
      confirmButtonText: '确定',
      cancelButtonText: '取消'
    }
  },
  home: '首页',
  login: '登录',
  components: '组件',
  count_to_page: '数字渐变',
  tables_page: '多功能表格',
  split_pane_page: '分割窗口',
  markdown_page: 'Markdown编辑器',
  editor_page: '富文本编辑器',
  icons_page: '自定义图标',
  img_cropper_page: '图片编辑器',
  update: '上传数据',
  join_page: 'QQ群',
  doc: '文档',
  update_table_page: '上传CSV文件',
  update_paste_page: '粘贴表格数据',
  multilevel: '多级菜单',
  directive_page: '指令',
  level_1: 'Level-1',
  level_2: 'Level-2',
  level_2_1: 'Level-2-1',
  level_2_3: 'Level-2-3',
  level_2_2: 'Level-2-2',
  level_2_2_1: 'Level-2-2-1',
  level_2_2_2: 'Level-2-2-2',
  excel: 'Excel',
  'upload-excel': '上传excel',
  'export-excel': '导出excel',
  tools_methods_page: '工具函数',
  drag_list_page: '拖拽列表',
  i18n_page: '多语言',
  modalTitle: '模态框题目',
  content: '这是模态框内容',
  buttonText: '显示模态框',
  'i18n-tip': '注：仅此页做了多语言，其他页面没有在多语言包中添加语言内容',
  error_store_page: '错误收集',
  error_logger_page: '错误日志',
  query: '带参路由',
  params: '动态路由',
  cropper_page: '图片裁剪',
  message_page: '消息中心',
  tree_table_page: '树状表格',
  org_tree_page: '组织结构树',
  drag_drawer_page: '可拖动抽屉',
  tree_select_page: '树状下拉选择器',

  // 订单交期
  order_delivery_date: '订单交期',
  // 看板查询
  order_query: '查询',
  gantt_board: '甘特图看板',
  production_line_query: '产线查询',
  production_controller: '生产管控',
  output_value_board: '产值看板',
  smt_board_query: 'SMT看板查询',
  smt_controller_board: 'SMT产线管理看板',
  ic_production_board: 'IC面生产看板',
  light_plane_query: '灯面生产看板',
  mc_solder_paste_board: 'MC锡膏看板',
  smt_solder_paste_board: 'SMT锡膏看板',
  rty: '直通率',
  spare_parts_materials: '备品配件物料管理',
  sop_query: 'SOP',
  
  customer_complaint: '客诉',
  customer_complaint_loss_list: '客诉损失明细表',
  // 模块
  module_manage: '模块',
  smt_plan_entry: 'SMT计划录入',
  smt_production_entry: 'SMT生产信息录入',
  solder_paste_operation: '锡膏操作',
  module_page: '模块页',
  // 模组
  module_group: '模组',
  production_line_scan_code: '产线扫码',
  rules_entry: '规则录入',
  carton_packing: '外箱装箱',
  inside_box_confirm: '内箱确认',
  stadium_displays: '球场屏',
  // end
  metal_plate: '钣金',
  mp_index:'首页',
  mp_basicinfo:'录入基本信息',
  mp_production:'录入生产信息',
  mp_modify:'修改生产信息',

  order_manage: '订单管理',
  spare_parts: '备品配件',
  contract: '合约',
  sales: '销售',
  hand_sample: '小样',
  // 仓库
  warehouse: '仓库',
  solder_paste_out_storage: '锡膏出库',
  solder_paste_put_storage: '锡膏入库',
  delete_put_storage: '删除入库信息',
  edit_sorage_number: '修改库位号',
  warehouse_material_management: '仓库物料管理',
  product_out_storage: '成品出库',
  product_put_storage: '成品入库',
  stock_index:'库存金额',
  stock_query:'月度库存金额',
  stock_erpquery:'查询ERP月度库存金额',

  // 设备
  Equipment: '设备',
  machine_room_operation: '空压机房运行状况',
  machine_room_summary_list: '空压机房汇总表',
  Equipment_NewIndex: '设备管理',
  production_line_equipment: '产线设备',

  // 环境
  environment: '环境',
  temperature_and_humidity: '全厂温湿度',
  temperature_and_humidity_summary_list: '温湿度汇总表',

  // 人力资源
  human_resources: '人力资源',
  personnel_daily_report: '人事日报表',
  labor_cost_week: '人工成本周对比',
  wastage_rate_month: '月流失率',
  recruitment_weekly: '招聘周报',
  departure_distribution: '离职员工工龄分布',
  membership_roster: '花名册',
  organizational_structure: '组织架构',
  excellent_teams_month: '月度优秀班组评选',
  departure_reason_survey: '离职原因调查',
  leave_record: '请假记录',
  system_user: '系统用户',
  KPI_7S_SummarizingRanking:'部门评比排名',
  KPI_7S_GradeStandardInput:'扣分标准录入',
  KPI_7S_RegionInput:'数据区域录入',
  KPI_7S_RecordInput:'部门班组扣分录入',
  KPI_7S_Summarizing:'日检记录查询',
  KPI_7S_Summarizing_Daily:'日/周/巡检汇总表',
  KPI_7S_DailyRecord:'日检记录查询',
  KPI_7S_Detail:'7S班组扣分详细表'
}
