//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JianHeMES.Areas.KongYaHT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kongyadbEntities : DbContext
    {
        public kongyadbEntities()
            : base("name=kongyadbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<airbottle1> airbottle1 { get; set; }
        public virtual DbSet<airbottle2> airbottle2 { get; set; }
        public virtual DbSet<airbottle3> airbottle3 { get; set; }
        public virtual DbSet<aircomp1> aircomp1 { get; set; }
        public virtual DbSet<aircomp2> aircomp2 { get; set; }
        public virtual DbSet<aircomp3> aircomp3 { get; set; }
        public virtual DbSet<dryer1> dryer1 { get; set; }
        public virtual DbSet<dryer2> dryer2 { get; set; }
        public virtual DbSet<headerpipe3inch> headerpipe3inch { get; set; }
        public virtual DbSet<headerpipe4inch> headerpipe4inch { get; set; }
        public virtual DbSet<room> room { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbsyslog> tbsyslog { get; set; }
        public virtual DbSet<THhistory> THhistory { get; set; }
    }
}
