//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JianHeMES.Areas.KongYaHT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbsyslog
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Operate { get; set; }
        public string Details { get; set; }
        public string Result { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> RecordTime { get; set; }
    }
}
